server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
spring:
  profiles:
    active: jdbc
  cloud:
    config:
      label: master
      enabled: true
      server:
        prefix: sccsj
        bootstrap: true
        default-profile: production
        jdbc:
          order: 1
          sql: SELECT pkey, pvalue from Property where application=? and profile=? and label=?
          enabled: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:postgresql://${SERVER_IP:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DB:sccsj}?currentSchema=${POSTGRESQL_SCHEMA:public}
    username: ${POSTGRESQL_USER:postgres}
    password: ${POSTGRESQL_PASSWORD:senocak}
  jpa:
    properties:
      hibernate:
        envers:
          audit_table_prefix: AU_
          revision_field_name: REV_ID
          revision_type_field_name: REV_TYPE
          store_data_at_delete: true
          default_schema: ${POSTGRESQL_SCHEMA:public}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 1000
    hibernate:
      ddl-auto: create-drop
  application:
    name: spring-cloud-config-server-jdbc
 #sql:
 #  init:
 #    mode: always
logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: debug
    org:
      hibernate:
        SQL: info
      springframework:
        security: debug
        web: error
  file:
    name: ./var/logs/app.log
springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
encrypt:
  #key: weedbcdskcbsdhjbc7876876
  keyStore:
    location: classpath:./config-server.jks
    password: my-s70r3-s3cr3t
    alias: config-server-key
    #secret: my-k34-s3cr3t
    #To generate .jks key visit: https://www.baeldung.com/spring-cloud-configuration